"""transaction fix value field name

Revision ID: 29c640b061ee
Revises: 0eed1fd11e7d
Create Date: 2023-10-01 23:16:09.759290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29c640b061ee'
down_revision: Union[str, None] = '0eed1fd11e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'balance', ['user_id'])
    op.add_column('transaction', sa.Column('value', sa.Integer(), nullable=False))
    op.drop_column('transaction', 'values')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('values', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('transaction', 'value')
    op.drop_constraint(None, 'balance', type_='unique')
    # ### end Alembic commands ###
